# Generated by Django 3.2 on 2021-04-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_personaldetail_registration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetail',
            name='registration_date',
        ),
    ]
